## The world of NumPy

In [1]:
import numpy as np

In [20]:
arr1 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])

In [21]:
# returning the size of array
arr1.size

12

In [22]:
#Shape of the array

arr1.shape

(3, 4)

In [23]:
arr1.dtype.name

'int64'

In [24]:
arr1.ndim

2

### Basic Arithmetic with NumPy

In [25]:
a = np.array([11,12,13])
b= np.array([1,2,3])
c = a - b
c

array([10, 10, 10])

In [26]:
d = a+b
d

array([12, 14, 16])

In [27]:
e = a * b
e

array([11, 24, 39])

### Squaring 

In [28]:
f = a ** 2
f

array([121, 144, 169])

In [29]:
# Trig on a series of data 

np.sin(f)

array([ 0.99881522, -0.49102159, -0.60199987])

In [30]:
# Conditions on array 

f % 2 ==0

array([False,  True, False], dtype=bool)

### Matrix multiplication got whole lot easier

In [33]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [35]:
arr2 = arr1 **2
arr2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [36]:
#3X4 cross 3x4 Matrix multiplication
arr1* arr2

array([[   1,    8,   27,   64],
       [ 125,  216,  343,  512],
       [ 729, 1000, 1331, 1728]])

In [38]:
#3x2
arr3 = np.array([[1,2],
                [3,4],
                [5,6]])

arr3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [39]:
#2X3
arr4 = np.array([[1,2,3],
                [4,5,6]])
arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
arr3*arr4

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [41]:
#dot does the traditional matrix multiplication
arr3.dot(arr4)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

### Slicing and Indexing the array

In [43]:
arr3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [45]:
arr3[0,0]

1

In [46]:
arr3[0,0:2]

array([1, 2])

In [48]:
arr3[:2,:2]

array([[1, 2],
       [3, 4]])

In [52]:
arr3[-1:,:2]

array([[5, 6]])

In [57]:
arr3[0]

array([1, 2])

In [58]:
arr3[0][1]

2

In [59]:
arr3[:,:]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [60]:
arr3[:,0]

array([1, 3, 5])

### Shape Manipulation

In [61]:
arr3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [62]:
arr3.ravel()

array([1, 2, 3, 4, 5, 6])

In [63]:
arr3.transpose()

array([[1, 3, 5],
       [2, 4, 6]])